Title = "NVMe"

[Parse]
PrintFormat = "normal" # normal short custom

[TracePoints]
Enabled = ["queue", "complete", "drvdata"]
CustomPoints = [
    [ "test", "Issue to device hardware" ],
    # [ "tag", "description"]
]

[Report]
Read = true
Write = true
Others = false

TimeSections = [
    [ "Q2N", "queue", "test" ],
    [ "N2C", "test", "complete" ]
]

[Report.Numbers]
Minimum = true
Maximum = true
Average = true

