Title = "NVMe"

[Parse]
Printformat = "normal" # normal short custom
# customformat = ""

# Possible tracepoint list of blktrace API:
#     queue backmerge frontmerge
#     getrq sleeprq requeue
#     issue complete plug
#     unplugio unplugtimer
#     insert split bounce remap abort
#
# note: drvdata is used for 'custom' points

[TracePoints]
Enabled = ["queue", "complete", "drvdata"]
CustomPoints = [
    [ "test", "Issue to device hardware" ],
    # [ "tag", "description"]
]

[Report]
# fioResultMerge = false
Read = true
Write = true
Others = false

TimeSections = [
    [ "Q2D", "queue", "test" ],
    [ "D2C", "test", "complete" ]
]

[Report.Numbers]
Minimum = true
Maximum = true
Average = true
# median = false
# percentiles = false
# distribution = false

